"""VideoGuru — Multi-Agent Video Production Pipeline Entry Point.

Bootstrap entry point for Google Agent Development Kit (ADK) application.
Supports running agent invocations, launching the ADK Web UI, inspecting
project configuration, and capturing user intent via RootGreeterAgent.
"""

from __future__ import annotations

import argparse
import asyncio
import os
import sys
import uuid
from typing import Optional

from google.adk.agents import BaseAgent
from google.adk.events import Event
from google.adk.runners import Runner
from google.genai import types

from agents import (
    RootGreeterAgent,
    create_root_greeter_agent,
    get_app,
    get_root_agent,
    root_agent,
)
from config import settings
from services import get_session_manager, get_session_service


class OfflineBootstrapAgent(BaseAgent):
    """Deterministic agent used for offline verification when Gemini API key is absent."""

    greeting: str = (
        "Hello from VideoGuru! Multi-Agent Video Production Pipeline is bootstrapped "
        "and ready. InMemorySessionService and ADK Runner are operational."
    )

    async def _run_async_impl(self, ctx):
        yield Event(
            author=self.name,
            content=types.Content(
                parts=[types.Part.from_text(text=self.greeting)]
            ),
        )


def print_project_info() -> None:
    """Print project configuration, paths, and agent metadata."""
    print("=" * 60)
    print("VideoGuru — Project Configuration & Status")
    print("=" * 60)
    print(f"App Name:            {settings.APP_NAME}")
    print(f"Base Directory:      {settings.BASE_DIR}")
    print(f"Media Input Dir:     {settings.MEDIA_INPUT_DIR}")
    print(f"Staging Dir:         {settings.STAGING_DIR}")
    print(f"Output Dir:          {settings.OUTPUT_DIR}")
    print(f"Gemini Model:        {settings.GEMINI_MODEL}")
    print(f"Whisper Model:       {settings.WHISPER_MODEL}")
    print(f"Max Loop Iterations: {settings.MAX_LOOP_ITERATIONS}")
    print(f"Web Host & Port:     {settings.WEB_HOST}:{settings.WEB_PORT}")
    print(f"Gemini API Key Set:  {'Yes' if bool(os.getenv('GEMINI_API_KEY')) else 'No (set GEMINI_API_KEY to enable live LLM)'}")
    print("-" * 60)
    print(f"Root Agent Name:     {root_agent.name}")
    print(f"Root Agent Desc:     {root_agent.description}")
    print(f"Session Service:     InMemorySessionService")
    print("=" * 60)


async def run_agent_turn(
    user_message: str = "Hello VideoGuru",
    user_id: str = settings.DEFAULT_USER_ID,
    session_id: Optional[str] = None,
    force_offline: bool = False,
) -> list[str]:
    """Execute a single agent invocation turn and return text responses.

    Args:
        user_message: Message content from the user.
        user_id: User identifier for session isolation.
        session_id: Unique session identifier; generated if None.
        force_offline: If True, runs RootGreeterAgent in deterministic offline mode.

    Returns:
        List of textual response strings generated by the agent.
    """
    if session_id is None:
        session_id = f"session_{uuid.uuid4().hex[:8]}"

    session_mgr = get_session_manager()
    session = await session_mgr.get_session(user_id=user_id, session_id=session_id)
    if session is None:
        session = await session_mgr.create_session(
            user_id=user_id,
            session_id=session_id,
            state={"initial_intent": user_message},
        )

    # Determine whether to run with live LLM agent or offline root greeter agent
    has_api_key = bool(os.getenv("GEMINI_API_KEY"))
    if not has_api_key or force_offline:
        active_agent = create_root_greeter_agent(name="videoguru", offline=True)
    else:
        active_agent = get_root_agent()

    runner = Runner(
        app_name=settings.APP_NAME,
        agent=active_agent,
        session_service=get_session_service(),
    )

    content = types.Content(parts=[types.Part.from_text(text=user_message)])
    responses: list[str] = []

    async for event in runner.run_async(
        user_id=user_id,
        session_id=session_id,
        new_message=content,
    ):
        if event.content and event.content.parts:
            for part in event.content.parts:
                if getattr(part, "text", None):
                    responses.append(part.text)

    return responses


def start_web_ui(host: str = settings.WEB_HOST, port: int = settings.WEB_PORT) -> None:
    """Launch the ADK FastAPI Web UI server."""
    import uvicorn
    from google.adk.cli.fast_api import get_fast_api_app

    print(f"Starting VideoGuru ADK Web UI on http://{host}:{port} ...")
    agents_dir = str(settings.BASE_DIR / "agents")
    fast_api_app = get_fast_api_app(
        agents_dir=agents_dir,
        session_service_uri="memory://",
        web=True,
        host=host,
        port=port,
    )
    uvicorn.run(fast_api_app, host=host, port=port)


def parse_arguments() -> argparse.Namespace:
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description="VideoGuru — Multi-Agent Video Production Pipeline (Google ADK)",
    )
    parser.add_argument(
        "--info",
        action="store_true",
        help="Display project configuration and agent status.",
    )
    parser.add_argument(
        "--run",
        nargs="?",
        const="Hello VideoGuru! Start session.",
        default=None,
        help="Run an agent turn with an optional user message prompt.",
    )
    parser.add_argument(
        "--theme",
        type=str,
        default=None,
        help="Directly specify the video theme/highlight for intent capture.",
    )
    parser.add_argument(
        "--scan-dir",
        type=str,
        default=None,
        metavar="DIR_PATH",
        help="Scan a local directory for video clips (.mp4, .mov, .avi, .mkv) and display basic metadata.",
    )
    parser.add_argument(
        "--web",
        action="store_true",
        help="Launch the ADK Web UI server.",
    )
    parser.add_argument(
        "--host",
        type=str,
        default=settings.WEB_HOST,
        help=f"Host for Web UI (default: {settings.WEB_HOST}).",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=settings.WEB_PORT,
        help=f"Port for Web UI (default: {settings.WEB_PORT}).",
    )
    parser.add_argument(
        "--offline",
        action="store_true",
        help="Force offline bootstrap execution without contacting Gemini API.",
    )
    return parser.parse_args()


def main() -> None:
    """Main CLI entry point."""
    args = parse_arguments()

    if args.info:
        print_project_info()
        return

    if args.scan_dir:
        from tools.directory_scanner import scan_local_directory_with_metadata

        print("=" * 60)
        print("VideoGuru: Scanning Local Directory for Media (SPEC-004)")
        print(f"Target Directory: {args.scan_dir}")
        print("=" * 60)
        try:
            files = scan_local_directory_with_metadata(args.scan_dir)
            if not files:
                print("No supported video files (.mp4, .mov, .avi, .mkv) found in directory.")
            else:
                print(f"Discovered {len(files)} video file(s):\n")
                total_bytes = 0
                for idx, f in enumerate(files, 1):
                    size_mb = f.file_size_bytes / (1024 * 1024)
                    total_bytes += f.file_size_bytes
                    print(f"  [{idx}] {f.file_name} ({size_mb:.2f} MB)")
                    print(f"      Path:     {f.path}")
                    print(f"      Modified: {f.last_modified_iso}")
                total_mb = total_bytes / (1024 * 1024)
                print("-" * 60)
                print(f"Total Media: {len(files)} file(s), {total_mb:.2f} MB")
            print("=" * 60)
        except Exception as exc:
            print(f"Scan failed: {exc}", file=sys.stderr)
            sys.exit(1)
        return

    if args.web:
        start_web_ui(host=args.host, port=args.port)
        return

    # Determine prompt from --theme or --run or default
    if args.theme is not None:
        user_prompt = args.theme
    elif args.run is not None:
        user_prompt = args.run
    else:
        user_prompt = "Hello VideoGuru! Start session."

    session_id = f"cli_{uuid.uuid4().hex[:8]}"

    print("=" * 60)
    print("VideoGuru: Executing Bootstrap Agent Turn")
    print(f"Input Prompt: {user_prompt}")
    print(f"Session ID:   {session_id}")
    print("=" * 60)

    try:
        responses = asyncio.run(
            run_agent_turn(
                user_message=user_prompt,
                session_id=session_id,
                force_offline=args.offline,
            )
        )
        for idx, resp in enumerate(responses, 1):
            print(f"[Agent Response {idx}]:\n{resp}")
        print("-" * 60)

        # Inspect captured state
        session_mgr = get_session_manager()
        state = asyncio.run(
            session_mgr.get_state(
                user_id=settings.DEFAULT_USER_ID,
                session_id=session_id,
            )
        )
        captured_theme = state.get("theme")
        if captured_theme:
            print(f"Session State Theme: '{captured_theme}' (Successfully captured)")
        else:
            print("Session State Theme: None (Awaiting creator input)")
        print("Turn completed successfully.")
    except Exception as exc:
        print(f"Execution failed: {exc}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
