"""VideoGuru — Multi-Agent Video Production Pipeline Entry Point.

Bootstrap entry point for Google Agent Development Kit (ADK) application.
Supports running agent invocations, launching the ADK Web UI, and inspecting
project configuration.
"""

from __future__ import annotations

import argparse
import asyncio
import os
import sys
import uuid
from typing import Optional

from google.adk.agents import BaseAgent
from google.adk.events import Event
from google.adk.runners import Runner
from google.genai import types

from agents import get_app, get_root_agent, root_agent
from config import settings
from services import get_session_manager, get_session_service


class OfflineBootstrapAgent(BaseAgent):
    """Deterministic agent used for offline verification when Gemini API key is absent."""

    greeting: str = (
        "Hello from VideoGuru! Multi-Agent Video Production Pipeline is bootstrapped "
        "and ready. InMemorySessionService and ADK Runner are operational."
    )

    async def _run_async_impl(self, ctx):
        yield Event(
            author=self.name,
            content=types.Content(
                parts=[types.Part.from_text(text=self.greeting)]
            ),
        )


def print_project_info() -> None:
    """Print project configuration, paths, and agent metadata."""
    print("=" * 60)
    print("VideoGuru — Project Configuration & Status")
    print("=" * 60)
    print(f"App Name:            {settings.APP_NAME}")
    print(f"Base Directory:      {settings.BASE_DIR}")
    print(f"Media Input Dir:     {settings.MEDIA_INPUT_DIR}")
    print(f"Staging Dir:         {settings.STAGING_DIR}")
    print(f"Output Dir:          {settings.OUTPUT_DIR}")
    print(f"Gemini Model:        {settings.GEMINI_MODEL}")
    print(f"Whisper Model:       {settings.WHISPER_MODEL}")
    print(f"Max Loop Iterations: {settings.MAX_LOOP_ITERATIONS}")
    print(f"Web Host & Port:     {settings.WEB_HOST}:{settings.WEB_PORT}")
    print(f"Gemini API Key Set:  {'Yes' if bool(os.getenv('GEMINI_API_KEY')) else 'No (set GEMINI_API_KEY to enable live LLM)'}")
    print("-" * 60)
    print(f"Root Agent Name:     {root_agent.name}")
    print(f"Root Agent Desc:     {root_agent.description}")
    print(f"Session Service:     InMemorySessionService")
    print("=" * 60)


async def run_agent_turn(
    user_message: str = "Hello VideoGuru",
    user_id: str = settings.DEFAULT_USER_ID,
    session_id: Optional[str] = None,
    force_offline: bool = False,
) -> list[str]:
    """Execute a single agent invocation turn and return text responses.

    Args:
        user_message: Message content from the user.
        user_id: User identifier for session isolation.
        session_id: Unique session identifier; generated if None.
        force_offline: If True, uses OfflineBootstrapAgent regardless of API key.

    Returns:
        List of textual response strings generated by the agent.
    """
    if session_id is None:
        session_id = f"session_{uuid.uuid4().hex[:8]}"

    session_mgr = get_session_manager()
    session = await session_mgr.get_session(user_id=user_id, session_id=session_id)
    if session is None:
        session = await session_mgr.create_session(
            user_id=user_id,
            session_id=session_id,
            state={"initial_intent": user_message},
        )

    # Determine whether to run with live LLM agent or offline bootstrap agent
    has_api_key = bool(os.getenv("GEMINI_API_KEY"))
    if not has_api_key or force_offline:
        active_agent = OfflineBootstrapAgent(name="videoguru")
    else:
        active_agent = get_root_agent()

    runner = Runner(
        app_name=settings.APP_NAME,
        agent=active_agent,
        session_service=get_session_service(),
    )

    content = types.Content(parts=[types.Part.from_text(text=user_message)])
    responses: list[str] = []

    async for event in runner.run_async(
        user_id=user_id,
        session_id=session_id,
        new_message=content,
    ):
        if event.content and event.content.parts:
            for part in event.content.parts:
                if getattr(part, "text", None):
                    responses.append(part.text)

    return responses


def start_web_ui(host: str = settings.WEB_HOST, port: int = settings.WEB_PORT) -> None:
    """Launch the ADK FastAPI Web UI server."""
    import uvicorn
    from google.adk.cli.fast_api import get_fast_api_app

    print(f"Starting VideoGuru ADK Web UI on http://{host}:{port} ...")
    agents_dir = str(settings.BASE_DIR / "agents")
    fast_api_app = get_fast_api_app(
        agents_dir=agents_dir,
        session_service_uri="memory://",
        web=True,
        host=host,
        port=port,
    )
    uvicorn.run(fast_api_app, host=host, port=port)


def parse_arguments() -> argparse.Namespace:
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description="VideoGuru — Multi-Agent Video Production Pipeline (Google ADK)",
    )
    parser.add_argument(
        "--info",
        action="store_true",
        help="Display project configuration and agent status.",
    )
    parser.add_argument(
        "--run",
        nargs="?",
        const="Hello VideoGuru! Start session.",
        default=None,
        help="Run an agent turn with an optional user message prompt.",
    )
    parser.add_argument(
        "--web",
        action="store_true",
        help="Launch the ADK Web UI server.",
    )
    parser.add_argument(
        "--host",
        type=str,
        default=settings.WEB_HOST,
        help=f"Host for Web UI (default: {settings.WEB_HOST}).",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=settings.WEB_PORT,
        help=f"Port for Web UI (default: {settings.WEB_PORT}).",
    )
    parser.add_argument(
        "--offline",
        action="store_true",
        help="Force offline bootstrap execution without contacting Gemini API.",
    )
    return parser.parse_args()


def main() -> None:
    """Main CLI entry point."""
    args = parse_arguments()

    if args.info:
        print_project_info()
        return

    if args.web:
        start_web_ui(host=args.host, port=args.port)
        return

    # If --run is passed or no specific mode selected, run an agent turn
    user_prompt = args.run if args.run is not None else "Hello VideoGuru! Start session."
    print("=" * 60)
    print("VideoGuru: Executing Bootstrap Agent Turn")
    print(f"Input Prompt: {user_prompt}")
    print("=" * 60)

    try:
        responses = asyncio.run(
            run_agent_turn(
                user_message=user_prompt,
                force_offline=args.offline,
            )
        )
        for idx, resp in enumerate(responses, 1):
            print(f"[Agent Response {idx}]:\n{resp}")
        print("-" * 60)
        print("Turn completed successfully.")
    except Exception as exc:
        print(f"Execution failed: {exc}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
