"""VideoGuru — Multi-Agent Video Production Pipeline Entry Point.

Bootstrap entry point for Google Agent Development Kit (ADK) application.
Supports running agent invocations, launching the ADK Web UI, inspecting
project configuration, and capturing user intent via RootGreeterAgent.
"""

from __future__ import annotations

import argparse
import asyncio
import os
import sys
import uuid
from typing import Optional

from google.adk.agents import BaseAgent
from google.adk.events import Event
from google.adk.runners import Runner
from google.genai import types

from agents import (
    RootGreeterAgent,
    create_root_greeter_agent,
    get_app,
    get_root_agent,
    root_agent,
)
from config import settings
from services import get_session_manager, get_session_service


class OfflineBootstrapAgent(BaseAgent):
    """Deterministic agent used for offline verification when Gemini API key is absent."""

    greeting: str = (
        "Hello from VideoGuru! Multi-Agent Video Production Pipeline is bootstrapped "
        "and ready. InMemorySessionService and ADK Runner are operational."
    )

    async def _run_async_impl(self, ctx):
        yield Event(
            author=self.name,
            content=types.Content(
                parts=[types.Part.from_text(text=self.greeting)]
            ),
        )


def print_project_info() -> None:
    """Print project configuration, paths, and agent metadata."""
    print("=" * 60)
    print("VideoGuru — Project Configuration & Status")
    print("=" * 60)
    print(f"App Name:            {settings.APP_NAME}")
    print(f"Base Directory:      {settings.BASE_DIR}")
    print(f"Media Input Dir:     {settings.MEDIA_INPUT_DIR}")
    print(f"Staging Dir:         {settings.STAGING_DIR}")
    print(f"Output Dir:          {settings.OUTPUT_DIR}")
    print(f"Gemini Model:        {settings.GEMINI_MODEL}")
    print(f"Whisper Model:       {settings.WHISPER_MODEL}")
    print(f"Max Loop Iterations: {settings.MAX_LOOP_ITERATIONS}")
    print(f"Web Host & Port:     {settings.WEB_HOST}:{settings.WEB_PORT}")
    print(f"Gemini API Key Set:  {'Yes' if bool(os.getenv('GEMINI_API_KEY')) else 'No (set GEMINI_API_KEY to enable live LLM)'}")
    print("-" * 60)
    print(f"Root Agent Name:     {root_agent.name}")
    print(f"Root Agent Desc:     {root_agent.description}")
    print(f"Session Service:     InMemorySessionService")
    print("=" * 60)


async def run_agent_turn(
    user_message: str = "Hello VideoGuru",
    user_id: str = settings.DEFAULT_USER_ID,
    session_id: Optional[str] = None,
    force_offline: bool = False,
) -> list[str]:
    """Execute a single agent invocation turn and return text responses.

    Args:
        user_message: Message content from the user.
        user_id: User identifier for session isolation.
        session_id: Unique session identifier; generated if None.
        force_offline: If True, runs RootGreeterAgent in deterministic offline mode.

    Returns:
        List of textual response strings generated by the agent.
    """
    if session_id is None:
        session_id = f"session_{uuid.uuid4().hex[:8]}"

    session_mgr = get_session_manager()
    session = await session_mgr.get_session(user_id=user_id, session_id=session_id)
    if session is None:
        session = await session_mgr.create_session(
            user_id=user_id,
            session_id=session_id,
            state={"initial_intent": user_message},
        )

    # Determine whether to run with live LLM agent or offline root greeter agent
    has_api_key = bool(os.getenv("GEMINI_API_KEY"))
    if not has_api_key or force_offline:
        active_agent = create_root_greeter_agent(name="videoguru", offline=True)
    else:
        active_agent = get_root_agent()

    runner = Runner(
        app_name=settings.APP_NAME,
        agent=active_agent,
        session_service=get_session_service(),
    )

    content = types.Content(parts=[types.Part.from_text(text=user_message)])
    responses: list[str] = []

    async for event in runner.run_async(
        user_id=user_id,
        session_id=session_id,
        new_message=content,
    ):
        if event.content and event.content.parts:
            for part in event.content.parts:
                if getattr(part, "text", None):
                    responses.append(part.text)

    return responses


def start_web_ui(host: str = settings.WEB_HOST, port: int = settings.WEB_PORT) -> None:
    """Launch the ADK FastAPI Web UI server."""
    import uvicorn
    from google.adk.cli.fast_api import get_fast_api_app

    print(f"Starting VideoGuru ADK Web UI on http://{host}:{port} ...")
    agents_dir = str(settings.BASE_DIR / "agents")
    fast_api_app = get_fast_api_app(
        agents_dir=agents_dir,
        session_service_uri="memory://",
        web=True,
        host=host,
        port=port,
    )
    uvicorn.run(fast_api_app, host=host, port=port)


def parse_arguments() -> argparse.Namespace:
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description="VideoGuru — Multi-Agent Video Production Pipeline (Google ADK)",
    )
    parser.add_argument(
        "--info",
        action="store_true",
        help="Display project configuration and agent status.",
    )
    parser.add_argument(
        "--run",
        nargs="?",
        const="Hello VideoGuru! Start session.",
        default=None,
        help="Run an agent turn with an optional user message prompt.",
    )
    parser.add_argument(
        "--theme",
        type=str,
        default=None,
        help="Directly specify the video theme/highlight for intent capture.",
    )
    parser.add_argument(
        "--scan-dir",
        type=str,
        default=None,
        metavar="DIR_PATH",
        help="Scan a local directory for video clips (.mp4, .mov, .avi, .mkv) and display basic metadata.",
    )
    parser.add_argument(
        "--extract-metadata",
        "-m",
        type=str,
        default=None,
        metavar="FILE_PATH",
        help="Extract video metadata using ffprobe and display ClipManifestEntry (SPEC-005).",
    )
    parser.add_argument(
        "--ingest-dir",
        "--ingest",
        type=str,
        default=None,
        metavar="DIR_PATH",
        help="Run Ingestion Agent on a directory to build and display the Clip Manifest (SPEC-006).",
    )
    parser.add_argument(
        "--validate-edl",
        type=str,
        default=None,
        metavar="EDL_JSON_PATH",
        help="Validate and inspect an Edit Decision List (EDL) JSON file (SPEC-007).",
    )
    parser.add_argument(
        "--analyze-clip",
        type=str,
        default=None,
        metavar="CLIP_PATH",
        help="Analyze a video clip using Gemini 2.0 Flash multimodal API (SPEC-008).",
    )
    parser.add_argument(
        "--clip-id",
        type=str,
        default=None,
        help="Optional explicit clip identifier for --analyze-clip.",
    )
    parser.add_argument(
        "--web",
        action="store_true",
        help="Launch the ADK Web UI server.",
    )
    parser.add_argument(
        "--host",
        type=str,
        default=settings.WEB_HOST,
        help=f"Host for Web UI (default: {settings.WEB_HOST}).",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=settings.WEB_PORT,
        help=f"Port for Web UI (default: {settings.WEB_PORT}).",
    )
    parser.add_argument(
        "--offline",
        action="store_true",
        help="Force offline bootstrap execution without contacting Gemini API.",
    )
    return parser.parse_args()


def main() -> None:
    """Main CLI entry point."""
    args = parse_arguments()

    if args.info:
        print_project_info()
        return

    if args.scan_dir:
        from tools.directory_scanner import scan_local_directory_with_metadata

        print("=" * 60)
        print("VideoGuru: Scanning Local Directory for Media (SPEC-004)")
        print(f"Target Directory: {args.scan_dir}")
        print("=" * 60)
        try:
            files = scan_local_directory_with_metadata(args.scan_dir)
            if not files:
                print("No supported video files (.mp4, .mov, .avi, .mkv) found in directory.")
            else:
                print(f"Discovered {len(files)} video file(s):\n")
                total_bytes = 0
                for idx, f in enumerate(files, 1):
                    size_mb = f.file_size_bytes / (1024 * 1024)
                    total_bytes += f.file_size_bytes
                    print(f"  [{idx}] {f.file_name} ({size_mb:.2f} MB)")
                    print(f"      Path:     {f.path}")
                    print(f"      Modified: {f.last_modified_iso}")
                total_mb = total_bytes / (1024 * 1024)
                print("-" * 60)
                print(f"Total Media: {len(files)} file(s), {total_mb:.2f} MB")
            print("=" * 60)
        except Exception as exc:
            print(f"Scan failed: {exc}", file=sys.stderr)
            sys.exit(1)
        return

    if args.extract_metadata:
        from tools.clip_metadata import extract_clip_metadata

        print("=" * 60)
        print("VideoGuru: Extracting Clip Metadata via ffprobe (SPEC-005)")
        print(f"Target Clip: {args.extract_metadata}")
        print("=" * 60)
        try:
            entry = extract_clip_metadata(args.extract_metadata)
            size_mb = entry.file_size_bytes / (1024 * 1024)
            print(f"Clip ID:        {entry.clip_id}")
            print(f"File Name:      {entry.file_name} ({size_mb:.2f} MB)")
            print(f"Absolute Path:  {entry.absolute_path}")
            print(f"Duration:       {entry.duration_seconds:.3f} s")
            print(f"Frame Rate:     {entry.frame_rate:.2f} fps")
            print(f"Resolution:     {entry.resolution} ({entry.width}x{entry.height})")
            print(f"Video Codec:    {entry.video_codec}")
            print(f"Audio Codec:    {entry.audio_codec or 'None'}")
            print(f"Has Audio:      {'Yes' if entry.has_audio else 'No'}")
            print("=" * 60)
        except Exception as exc:
            print(f"Metadata extraction failed: {exc}", file=sys.stderr)
            sys.exit(1)
        return

    if args.ingest_dir:
        from tools.ingestion_tools import build_clip_manifest

        print("=" * 60)
        print("VideoGuru: Media Ingestion & Clip Manifest Construction (SPEC-006)")
        print(f"Target Directory: {args.ingest_dir}")
        print("=" * 60)
        try:
            manifest = build_clip_manifest(args.ingest_dir)
            if not manifest:
                print("No video clips found or ingested from directory.")
            else:
                total_duration = sum(c.duration_seconds for c in manifest)
                total_bytes = sum(c.file_size_bytes for c in manifest)
                total_mb = total_bytes / (1024 * 1024)
                print(f"Ingested {len(manifest)} clip(s) [Total: {total_duration:.2f}s, {total_mb:.2f} MB]:\n")
                for idx, c in enumerate(manifest, 1):
                    audio_str = f"audio={c.audio_codec}" if c.has_audio else "silent"
                    size_mb = c.file_size_bytes / (1024 * 1024)
                    print(f"  [{idx}] {c.clip_id}: {c.file_name} ({size_mb:.2f} MB)")
                    print(f"      Resolution: {c.resolution} ({c.width}x{c.height}) @ {c.frame_rate:.2f}fps")
                    print(f"      Duration:   {c.duration_seconds:.3f} s")
                    print(f"      Codecs:     video={c.video_codec}, {audio_str}")
                    print(f"      Path:       {c.absolute_path}")
                print("-" * 60)
                print(f"Clip manifest successfully assembled with {len(manifest)} entries.")
            print("=" * 60)
        except Exception as exc:
            print(f"Ingestion failed: {exc}", file=sys.stderr)
            sys.exit(1)
        return

    if args.validate_edl:
        from schemas.edl import EditDecisionList

        print("=" * 60)
        print("VideoGuru: Validating Edit Decision List (SPEC-007)")
        print(f"Target File: {args.validate_edl}")
        print("=" * 60)
        try:
            edl = EditDecisionList.from_file(args.validate_edl)
            print(f"EDL Valid: {len(edl)} cut(s) loaded successfully.")
            print(f"Total Duration:    {edl.total_duration:.2f} s")
            print(f"Unique Clips Used: {len(edl.clip_references)} ({', '.join(sorted(edl.clip_references))})")
            print("-" * 60)
            for idx, entry in enumerate(edl, 1):
                print(f"  [{idx}] Clip: {entry.file_reference} ({entry.start_trim:.2f}s -> {entry.end_trim:.2f}s | {entry.duration:.2f}s) | Transition: {entry.transition_intent.value}")
                print(f"      Rationale: {entry.scene_rationale}")
            print("=" * 60)
        except Exception as exc:
            print(f"EDL validation failed: {exc}", file=sys.stderr)
            sys.exit(1)
        return

    if args.analyze_clip:
        from tools.video_analysis import analyze_clip

        analysis_theme = args.theme or "General highlights and engaging moments"
        print("=" * 60)
        print("VideoGuru: Analyzing Video Clip via Gemini 2.0 Flash (SPEC-008)")
        print(f"Target Clip:    {args.analyze_clip}")
        print(f"Theme:          {analysis_theme}")
        print(f"Execution Mode: {'Offline / Mock' if args.offline else 'Gemini Multimodal Live API'}")
        print("=" * 60)
        try:
            entry = analyze_clip(
                clip_path=args.analyze_clip,
                theme=analysis_theme,
                clip_id=args.clip_id,
                offline=args.offline,
            )
            score_str = f"{entry.engagement_score:.1f}/10.0" if entry.engagement_score is not None else "N/A"
            print(f"File Reference:   {entry.file_reference}")
            print(f"Start Trim:       {entry.start_trim:.3f} s")
            print(f"End Trim:         {entry.end_trim:.3f} s")
            print(f"Segment Duration: {entry.duration:.3f} s")
            print(f"Transition:       {entry.transition_intent.value}")
            print(f"Engagement Score: {score_str}")
            print(f"Scene Rationale:  {entry.scene_rationale}")
            print("=" * 60)
        except Exception as exc:
            print(f"Clip analysis failed: {exc}", file=sys.stderr)
            sys.exit(1)
        return

    if args.web:
        start_web_ui(host=args.host, port=args.port)
        return

    # Determine prompt from --theme or --run or default
    if args.theme is not None:
        user_prompt = args.theme
    elif args.run is not None:
        user_prompt = args.run
    else:
        user_prompt = "Hello VideoGuru! Start session."

    session_id = f"cli_{uuid.uuid4().hex[:8]}"

    print("=" * 60)
    print("VideoGuru: Executing Bootstrap Agent Turn")
    print(f"Input Prompt: {user_prompt}")
    print(f"Session ID:   {session_id}")
    print("=" * 60)

    try:
        responses = asyncio.run(
            run_agent_turn(
                user_message=user_prompt,
                session_id=session_id,
                force_offline=args.offline,
            )
        )
        for idx, resp in enumerate(responses, 1):
            print(f"[Agent Response {idx}]:\n{resp}")
        print("-" * 60)

        # Inspect captured state
        session_mgr = get_session_manager()
        state = asyncio.run(
            session_mgr.get_state(
                user_id=settings.DEFAULT_USER_ID,
                session_id=session_id,
            )
        )
        captured_theme = state.get("theme")
        if captured_theme:
            print(f"Session State Theme: '{captured_theme}' (Successfully captured)")
        else:
            print("Session State Theme: None (Awaiting creator input)")
        print("Turn completed successfully.")
    except Exception as exc:
        print(f"Execution failed: {exc}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
