"""Human-Centric Critic Schemas for VideoGuru (SPEC-011).

Defines Pydantic models for human viewer, thumbnail, and narrative evaluation:
- Hook30sMetrics: Evaluates the critical first 30 seconds for AVD potential and theme setup.
- ThumbnailMetrics: Identifies and evaluates candidate thumbnail frames for YouTube CTR viability.
- StorytellingMetrics: Evaluates narrative arc, emotional progression, and human resonance.
- CriticReviewResult: Comprehensive evaluation report containing scores, pass/fail status,
  candidate thumbnail recommendation, detailed feedback, and loop control action (exit_loop vs append_to_state).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Optional, Sequence, Union

from pydantic import BaseModel, Field


class Hook30sMetrics(BaseModel):
    """Metrics evaluating the critical first 30 seconds for viewer retention and AVD potential."""

    duration_analyzed: float = Field(
        ...,
        ge=0.0,
        description="Total duration of the introductory window analyzed (up to 30.0 seconds).",
    )
    cut_count_in_30s: int = Field(
        ...,
        ge=0,
        description="Number of cuts occurring within the first 30 seconds.",
    )
    hook_avd_score: float = Field(
        ...,
        ge=0.0,
        le=10.0,
        description="Estimated Average View Duration (AVD) score (0.0 to 10.0) based on early pacing.",
    )
    theme_setup_score: float = Field(
        ...,
        ge=0.0,
        le=10.0,
        description="Score (0.0 to 10.0) evaluating how effectively the video establishes the creator's theme early.",
    )
    has_dead_air: bool = Field(
        ...,
        description="True if slow passages or cuts exceeding 8.0s without visual change exist in the first 30s.",
    )
    is_engaging: bool = Field(
        ...,
        description="True if the 30-second window satisfies human engagement criteria (score >= 7.0 and no dead air).",
    )


class ThumbnailMetrics(BaseModel):
    """Metrics and recommendation for YouTube thumbnail Click-Through Rate (CTR) viability."""

    candidate_clip_reference: str = Field(
        ...,
        description="The clip_id of the most visually compelling candidate cut for a thumbnail.",
    )
    candidate_timestamp: float = Field(
        ...,
        ge=0.0,
        description="Recommended offset timestamp (seconds into clip) to capture the thumbnail frame.",
    )
    visual_interest_score: float = Field(
        ...,
        ge=0.0,
        le=10.0,
        description="Visual clarity, contrast, and subject focus score (0.0 to 10.0).",
    )
    ctr_score: float = Field(
        ...,
        ge=0.0,
        le=10.0,
        description="Estimated Click-Through Rate (CTR) viability score (0.0 to 10.0).",
    )
    thumbnail_rationale: str = Field(
        ...,
        description="Justification explaining why this frame/moment will drive high viewer click-through.",
    )
    is_viable: bool = Field(
        ...,
        description="True if the video contains at least one viable high-CTR thumbnail candidate (score >= 7.0).",
    )


class StorytellingMetrics(BaseModel):
    """Metrics evaluating the emotional narrative arc and viewer payoff."""

    narrative_arc_score: float = Field(
        ...,
        ge=0.0,
        le=10.0,
        description="Score (0.0 to 10.0) evaluating logical beginning, middle, and climax progression.",
    )
    emotional_peak_score: float = Field(
        ...,
        ge=0.0,
        le=10.0,
        description="Score (0.0 to 10.0) evaluating presence of high-energy, humorous, or impactful moments.",
    )
    human_resonance_score: float = Field(
        ...,
        ge=0.0,
        le=10.0,
        description="Score (0.0 to 10.0) evaluating natural human appeal and relatable emotional tone.",
    )
    theme_alignment_score: float = Field(
        ...,
        ge=0.0,
        le=10.0,
        description="Score (0.0 to 10.0) evaluating fidelity to the creator's stated theme.",
    )


class CriticReviewResult(BaseModel):
    """Comprehensive human-centric review report generated by CriticAgent (SPEC-011)."""

    passed: bool = Field(
        ...,
        description="True if the EDL satisfies human-centric standards (score >= 7.0, engaging 30s hook, viable thumbnail).",
    )
    score: float = Field(
        ...,
        ge=0.0,
        le=10.0,
        description="Overall composite human-centric score (0.0 to 10.0).",
    )
    hook_30s_score: float = Field(
        ...,
        ge=0.0,
        le=10.0,
        description="30-second hook / AVD score (0.0 to 10.0).",
    )
    thumbnail_score: float = Field(
        ...,
        ge=0.0,
        le=10.0,
        description="Thumbnail CTR viability score (0.0 to 10.0).",
    )
    storytelling_score: float = Field(
        ...,
        ge=0.0,
        le=10.0,
        description="Emotional engagement and narrative arc score (0.0 to 10.0).",
    )
    feedback: str = Field(
        ...,
        description="Detailed review feedback critique formatted in markdown for human review or editing loop.",
    )
    recommendations: list[str] = Field(
        default_factory=list,
        description="Specific actionable recommendations for refining the EDL from a viewer perspective.",
    )
    candidate_thumbnail: ThumbnailMetrics = Field(
        ...,
        description="Recommended thumbnail frame candidate and CTR analysis.",
    )
    hook_30s_metrics: Hook30sMetrics = Field(
        ...,
        description="Detailed breakdown of the opening 30-second window.",
    )
    storytelling_metrics: StorytellingMetrics = Field(
        ...,
        description="Detailed breakdown of narrative and emotional resonance.",
    )
    loop_action: str = Field(
        ...,
        description="Autonomous loop control action taken: 'exit_loop' on pass, 'append_to_state' on revision needed.",
    )

    def to_dict(self) -> dict[str, Any]:
        """Serialize result to a dictionary representation."""
        return self.model_dump()

    def to_json(self, indent: int = 2) -> str:
        """Serialize result to a formatted JSON string."""
        return json.dumps(self.model_dump(), indent=indent)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> CriticReviewResult:
        """Deserialize a CriticReviewResult from a dictionary."""
        return cls.model_validate(data)

    @classmethod
    def from_json(cls, json_str: str) -> CriticReviewResult:
        """Deserialize a CriticReviewResult from a JSON string."""
        return cls.model_validate(json.loads(json_str))
