"""Algorithmic Review Schemas for VideoGuru (SPEC-010).

Defines Pydantic models for YouTube recommendation algorithm evaluation:
- PacingMetrics: Quantitative metrics evaluating cut frequency, pacing variance, and cadence.
- HookMetrics: Metrics evaluating the first 5 seconds for opening engagement and drop-off prevention.
- RetentionMetrics: Metrics evaluating total duration, transition flow, and retention curve.
- AlgorithmicReviewResult: Comprehensive review report containing scores, pass/fail status,
  detailed feedback string, and actionable recommendations.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Optional, Sequence, Union

from pydantic import BaseModel, Field


class PacingMetrics(BaseModel):
    """Quantitative pacing and cut frequency metrics for an Edit Decision List."""

    avg_cut_duration: float = Field(
        ...,
        ge=0.0,
        description="Average cut duration across all timeline cuts in seconds.",
    )
    cut_count: int = Field(
        ...,
        ge=0,
        description="Total number of cuts in the Edit Decision List.",
    )
    cuts_per_minute: float = Field(
        ...,
        ge=0.0,
        description="Cut frequency normalized to cuts per minute (CPM).",
    )
    max_cut_duration: float = Field(
        ...,
        ge=0.0,
        description="Duration of the longest individual cut in seconds.",
    )
    min_cut_duration: float = Field(
        ...,
        ge=0.0,
        description="Duration of the shortest individual cut in seconds.",
    )
    pacing_variance: float = Field(
        default=0.0,
        ge=0.0,
        description="Standard deviation of cut durations indicating dynamic cadence rhythm.",
    )
    excessive_cuts_count: int = Field(
        default=0,
        ge=0,
        description="Number of cuts exceeding 10.0 seconds without visual change (retention drop-off risks).",
    )


class HookMetrics(BaseModel):
    """Opening hook metrics evaluating the first 5 seconds of the video."""

    hook_duration: float = Field(
        ...,
        ge=0.0,
        description="Duration of the opening cut in seconds.",
    )
    first_cut_engagement: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=10.0,
        description="Engagement score of the first cut evaluated by multimodal analysis.",
    )
    hook_score: float = Field(
        ...,
        ge=0.0,
        le=10.0,
        description="Opening hook strength score (0.0 to 10.0) evaluating immediate hook power.",
    )
    is_punchy: bool = Field(
        ...,
        description="True if the first cut is under 5.0 seconds and has strong immediate energy.",
    )


class RetentionMetrics(BaseModel):
    """Timeline retention curve and transition flow metrics."""

    total_duration: float = Field(
        ...,
        ge=0.0,
        description="Total duration of the curated timeline in seconds.",
    )
    retention_score: float = Field(
        ...,
        ge=0.0,
        le=10.0,
        description="Estimated audience retention curve score (0.0 to 10.0).",
    )
    transition_diversity_score: float = Field(
        ...,
        ge=0.0,
        le=10.0,
        description="Score evaluating smooth transition flow and variety (0.0 to 10.0).",
    )


class AlgorithmicReviewResult(BaseModel):
    """Comprehensive algorithmic review report generated by ReviewerAgent (SPEC-010)."""

    passed: bool = Field(
        ...,
        description="True if the EDL satisfies YouTube algorithm benchmarks (score >= 7.0 and hook passed).",
    )
    score: float = Field(
        ...,
        ge=0.0,
        le=10.0,
        description="Overall composite algorithmic score (0.0 to 10.0).",
    )
    hook_score: float = Field(
        ...,
        ge=0.0,
        le=10.0,
        description="Hook strength score (0.0 to 10.0) evaluating the critical first 5 seconds.",
    )
    pacing_score: float = Field(
        ...,
        ge=0.0,
        le=10.0,
        description="Pacing score (0.0 to 10.0) evaluating cut frequency and energy flow.",
    )
    retention_score: float = Field(
        ...,
        ge=0.0,
        le=10.0,
        description="Retention score (0.0 to 10.0) evaluating narrative arc and drop-off prevention.",
    )
    feedback: str = Field(
        ...,
        description="Detailed review feedback critique formatted in markdown for the editing loop.",
    )
    recommendations: list[str] = Field(
        default_factory=list,
        description="Specific actionable recommendations for refining the EDL.",
    )
    pacing_metrics: PacingMetrics = Field(
        ...,
        description="Quantitative pacing breakdown.",
    )
    hook_metrics: HookMetrics = Field(
        ...,
        description="Quantitative opening hook breakdown.",
    )
    retention_metrics: RetentionMetrics = Field(
        ...,
        description="Quantitative retention breakdown.",
    )

    def to_dict(self) -> dict[str, Any]:
        """Serialize result to a dictionary representation."""
        return self.model_dump()

    def to_json(self, indent: int = 2) -> str:
        """Serialize result to a formatted JSON string."""
        return json.dumps(self.model_dump(), indent=indent)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> AlgorithmicReviewResult:
        """Deserialize an AlgorithmicReviewResult from a dictionary."""
        return cls.model_validate(data)

    @classmethod
    def from_json(cls, json_str: str) -> AlgorithmicReviewResult:
        """Deserialize an AlgorithmicReviewResult from a JSON string."""
        return cls.model_validate(json.loads(json_str))
